### PR TITLE
MSE + EMEv1+OpenCDM playback not starting fixes #336 

### LINKED ISSUE #336: Encrypted content playback with EMEv1+OpenCDM+MSE does not work
When we try playing encrypted DASH content with MSE, the license is acquired, key is added but playback/decryption does not start. It seems like drm-session event does not reach the gstreamer decryptor instance since emitOpenCDMSession() is not implemented in MediaPlayerPrivateGstreamerMSE class.

### PR DESCRIPTION
**Pull request by goruklu**
added emitOpenCDMSession() in MediaPlayerPrivateGStreamerMSE

### CODE REVIEW

File: Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp [hunk 1]
```diff
@@ -96,9 +96,14 @@ static gboolean webKitMediaOpenCDMDecryptorHandleKeyResponse(WebKitMediaCommonEn
     WebKitOpenCDMDecryptPrivate* priv = GST_WEBKIT_OPENCDM_DECRYPT_GET_PRIVATE(WEBKIT_OPENCDM_DECRYPT(self));
     ASSERT(temporarySession);
 
-    priv->m_session = temporarySession.get();
-    priv->m_openCdm = std::make_unique<media::OpenCdm>();
-    priv->m_openCdm->SelectSession(priv->m_session.utf8().data());
+    if(priv->m_session != temporarySession.get() ) {
+        priv->m_session = temporarySession.get();
+        GST_WARNING_OBJECT(self, "selecting session %s", priv->m_session.utf8().data());
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp]: This is not a WARNING, INFO at most.

File: Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp [hunk 2]
```diff
@@ -96,9 +96,14 @@ static gboolean webKitMediaOpenCDMDecryptorHandleKeyResponse(WebKitMediaCommonEn
...
+        priv->m_openCdm = std::make_unique<media::OpenCdm>();
+        priv->m_openCdm->SelectSession(priv->m_session.utf8().data());
+    }else{
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp]: Remove the braces of the else. It goes against WebKit coding guidelines.

File: Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp [hunk 3]
```diff
@@ -96,9 +96,14 @@ static gboolean webKitMediaOpenCDMDecryptorHandleKeyResponse(WebKitMediaCommonEn
...
+        GST_WARNING_OBJECT(self, "session already selected! %s", priv->m_session.utf8().data());
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp]: This is not a WARNING either, DEBUG maybe.

File: Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp [hunk 4]
```diff
@@ -54,6 +54,13 @@
 #include "PlayreadySession.h"
 #endif
 
+#if ENABLE(LEGACY_ENCRYPTED_MEDIA_V1) || ENABLE(LEGACY_ENCRYPTED_MEDIA)
+#if USE(OCDM)
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp]: Make these two lines a single one as you do yourself below.

File: Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp [hunk 5]
```diff
@@ -872,6 +879,29 @@ void MediaPlayerPrivateGStreamerMSE::emitPlayReadySession(PlayreadySession* sess
 #endif
 #endif
 
+#if (ENABLE(LEGACY_ENCRYPTED_MEDIA) || ENABLE(LEGACY_ENCRYPTED_MEDIA_V1)) && USE(OCDM)
+void MediaPlayerPrivateGStreamerMSE::emitOpenCDMSession()
+{
+    if (!m_cdmSession)
+        return;
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp]: Add an empty line after this.

File: Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp [hunk 6]
```diff
@@ -872,6 +879,29 @@ void MediaPlayerPrivateGStreamerMSE::emitPlayReadySession(PlayreadySession* sess
...
+#if ENABLE(LEGACY_ENCRYPTED_MEDIA)
+    CDMSessionOpenCDM* cdmSession = static_cast<CDMSessionOpenCDM*>(m_cdmSession);
+#else
+    CDMSessionOpenCDM* cdmSession = static_cast<CDMSessionOpenCDM*>(m_cdmSession.get());
+#endif // ENABLE(LEGACY_ENCRYPTED_MEDIA)
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp]: It is not the first time I see this code pattern because of the duality of m_cdmSession between V1 and V2. Please refactor it into a function:
CDMSessionOpenCDM* getOpenCDMSession() { ... }

File: Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp [hunk 7]
```diff
@@ -872,6 +879,29 @@ void MediaPlayerPrivateGStreamerMSE::emitPlayReadySession(PlayreadySession* sess
...
+    const String& sessionId = cdmSession->sessionId();
+    if (sessionId.isEmpty())
+        return;
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp]: Add a line after this

File: Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp [hunk 8]
```diff
@@ -872,6 +879,29 @@ void MediaPlayerPrivateGStreamerMSE::emitPlayReadySession(PlayreadySession* sess
...
+    for (auto it : m_appendPipelinesMap)
+    {
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp]: This bracket is misplaced.

File: Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.h [hunk 9]
```diff
@@ -269,6 +269,10 @@ class MediaPlayerPrivateGStreamerBase : public MediaPlayerPrivateInterface
     Condition m_drawCondition;
     Lock m_drawMutex;
 #endif
+#if ENABLE(LEGACY_ENCRYPTED_MEDIA_V1) && USE(OPENCDM)
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.h]: If you honor my comment below, you won't need to move this, just make the getter function protected.

File: pr_new.patch [hunk 10]
```diff
@@ -0,0 +1,125 @@
+diff --git a/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp b/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp
```
Comment (calvaris) [inline pr_new.patch]: What is this file?

File: Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp [hunk 11]
```diff
@@ -1568,15 +1568,21 @@ void MediaPlayerPrivateGStreamerBase::emitPlayReadySession(PlayreadySession* ses
 #endif // USE(PLAYREADY)
 
 #if USE(OPENCDM)
-void MediaPlayerPrivateGStreamerBase::emitOpenCDMSession()
+CDMSessionOpenCDM* MediaPlayerPrivateGStreamerBase::getOpenCDMSession()
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp]: Oh, I'm sorry because this one is my fault. WebKit guidelines specify that this kind of methods should not be called as getOpenCDMSession() but as openCDMSession()

File: Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp [hunk 12]
```diff
@@ -1568,15 +1568,21 @@ void MediaPlayerPrivateGStreamerBase::emitPlayReadySession(PlayreadySession* ses
...
 {
-    if (!m_cdmSession)
-        return;
 #if ENABLE(LEGACY_ENCRYPTED_MEDIA)
-    CDMSessionOpenCDM* cdmSession = static_cast<CDMSessionOpenCDM*>(m_cdmSession);
+    return static_cast<CDMSessionOpenCDM*>(m_cdmSession);
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp]: In both casts we shouldn't use static but dynamic_cast.

File: Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp [hunk 13]
```diff
@@ -96,9 +96,14 @@ static gboolean webKitMediaOpenCDMDecryptorHandleKeyResponse(WebKitMediaCommonEn
     WebKitOpenCDMDecryptPrivate* priv = GST_WEBKIT_OPENCDM_DECRYPT_GET_PRIVATE(WEBKIT_OPENCDM_DECRYPT(self));
     ASSERT(temporarySession);
 
-    priv->m_session = temporarySession.get();
-    priv->m_openCdm = std::make_unique<media::OpenCdm>();
-    priv->m_openCdm->SelectSession(priv->m_session.utf8().data());
+    if(priv->m_session != temporarySession.get() ) {
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp]: Leave a space: if (

File: Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp [hunk 14]
```diff
@@ -96,9 +96,14 @@ static gboolean webKitMediaOpenCDMDecryptorHandleKeyResponse(WebKitMediaCommonEn
...
+        priv->m_session = temporarySession.get();
+        GST_INFO_OBJECT(self, "selecting session %s", priv->m_session.utf8().data());
+        priv->m_openCdm = std::make_unique<media::OpenCdm>();
+        priv->m_openCdm->SelectSession(priv->m_session.utf8().data());
+    } else
+        GST_INFO_OBJECT(self, "session already selected! %s", priv->m_session.utf8().data());
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp]: "session %s already selected"

File: Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp [hunk 15]
```diff
@@ -872,6 +877,26 @@ void MediaPlayerPrivateGStreamerMSE::emitPlayReadySession(PlayreadySession* sess
...
+    const String& sessionId = cdmSession->sessionId();
+    if (sessionId.isEmpty())
+        return;
+
+    for (auto it : m_appendPipelinesMap) {
+            gst_element_send_event(it.value->pipeline(), gst_event_new_custom(GST_EVENT_CUSTOM_DOWNSTREAM_OOB,
+                gst_structure_new("drm-session", "session", G_TYPE_STRING, sessionId.utf8().data(), nullptr)));
+            it.value->setAppendState(AppendPipeline::AppendState::Ongoing);
+    }
+    GST_DEBUG("emitted OCDM session on pipeline");
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp]: Call is OpenCDM. I refactored this on V3 to avoid abbreviating to OCDM. I am not going to force changing OCDM to OpenCDM everywhere but this place does not need to keep that outdated naming.

File: Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp (hunk 12 above)
Comment (goruklu) [inline Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp]: dynamic_cast is not allowed: `error: ‘dynamic_cast’ not permitted with -fno-rtti`

File: Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp [hunk 16]
```diff
@@ -96,9 +96,14 @@ static gboolean webKitMediaOpenCDMDecryptorHandleKeyResponse(WebKitMediaCommonEn
...
-    priv->m_session = temporarySession.get();
-    priv->m_openCdm = std::make_unique<media::OpenCdm>();
-    priv->m_openCdm->SelectSession(priv->m_session.utf8().data());
+    if (priv->m_session != temporarySession.get() ) {
+        priv->m_session = temporarySession.get();
+        GST_INFO_OBJECT(self, "selecting session %s", priv->m_session.utf8().data());
+        priv->m_openCdm = std::make_unique<media::OpenCdm>();
+        priv->m_openCdm->SelectSession(priv->m_session.utf8().data());
+    } else
+        GST_INFO_OBJECT(self, "session %s already selected!", priv->m_session.utf8().data());
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/eme/WebKitOpenCDMDecryptorGStreamer.cpp]: Please, remove the ! I would have done it myself but since I detected some other serious issue I'll let you do this too :smile:

File: Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp [hunk 17]
```diff
@@ -872,6 +877,26 @@ void MediaPlayerPrivateGStreamerMSE::emitPlayReadySession(PlayreadySession* sess
 #endif
 #endif
 
+#if (ENABLE(LEGACY_ENCRYPTED_MEDIA) || ENABLE(LEGACY_ENCRYPTED_MEDIA_V1)) && USE(OCDM)
+void MediaPlayerPrivateGStreamerMSE::emitOpenCDMSession()
+{
+    if (!m_cdmSession)
+        return;
+
+    CDMSessionOpenCDM* cdmSession = getOpenCDMSession();
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/mse/MediaPlayerPrivateGStreamerMSE.cpp]: This function shouldn't exist, right? We agreed on renaming it to openCDMSession.

File: Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp [hunk 18]
```diff
@@ -1568,15 +1568,24 @@ void MediaPlayerPrivateGStreamerBase::emitPlayReadySession(PlayreadySession* ses
...
-void MediaPlayerPrivateGStreamerBase::emitOpenCDMSession()
+CDMSessionOpenCDM* MediaPlayerPrivateGStreamerBase::openCDMSession()
 {
     if (!m_cdmSession)
-        return;
+        return nullptr;
+
 #if ENABLE(LEGACY_ENCRYPTED_MEDIA)
-    CDMSessionOpenCDM* cdmSession = static_cast<CDMSessionOpenCDM*>(m_cdmSession);
+    return static_cast<CDMSessionOpenCDM*>(m_cdmSession);
```
Comment (calvaris) [inline Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp]: We should do this a downcast but it involves boilerplate and I won't bother about this now unless we get nasty crashes.
